alcoholarm <- read.table("./Data/alcoholarm.txt", header=T, encoding='UTF-8')
alcoholtobacco <- read.table("./Data/alcoholtobacco.txt", header=T, encoding='UTF-8')
allentest <- read.table("./Data/allentest.txt", header=T, encoding='UTF-8')
allentestn23 <- read.table("./Data/allentestn23.txt", header=T, encoding='UTF-8')
alligator <- read.table("./Data/alligator.txt", header=T, encoding='UTF-8')
alphapluto <- read.table("./Data/alphapluto.txt", header=T, encoding='UTF-8')
anscombe <- read.table("./Data/anscombe.txt", header=T, encoding='UTF-8')
babybirds <- read.table("./Data/babybirds.txt", header=T, encoding='UTF-8')
birthsmokers <- read.table("./Data/birthsmokers.txt", header=T, encoding='UTF-8')
blaisdell <- read.table("./Data/blaisdell.txt", header=T, encoding='UTF-8')
bldgstories <- read.table("./Data/bldgstories.txt", header=T, encoding='UTF-8')
bloodpress <- read.table("./Data/bloodpress.txt", header=T, encoding='UTF-8')
bluegills <- read.table("./Data/bluegills.txt", header=T, encoding='UTF-8')
bodyfat <- read.table("./Data/bodyfat.txt", header=T, encoding='UTF-8')
ca_learning <- read.table("./Data/ca_learning.txt", header=T, encoding='UTF-8')
carstopping <- read.table("./Data/carstopping.txt", header=T, encoding='UTF-8')
cement <- read.table("./Data/cement.txt", header=T, encoding='UTF-8')
census <- read.table("./Data/us_census.txt", header=T, encoding='UTF-8')
coolhearts <- read.table("./Data/coolhearts.txt", header=T, encoding='UTF-8')
cordblood <- read.table("./Data/leadcord.txt", header=T, encoding='UTF-8')
corrosion <- read.table("./Data/corrosion.txt", header=T, encoding='UTF-8')
depression <- read.table("./Data/depression.txt", header=T, encoding='UTF-8')
disease <- read.table("./Data/DiseaseOutbreak.txt", header=T, encoding='UTF-8')
earthquakes <- read.table("./Data/earthquakes.txt", header=T, encoding='UTF-8')
employee <- read.table("./Data/employee.txt", header=T, encoding='UTF-8')
exerimmun <- read.table("./Data/exerimmun.txt", header=T, encoding='UTF-8')
galton <- read.table("./Data/galton.txt", header=T, encoding='UTF-8')
google <- read.table("./Data/google_stock.txt", header=T, encoding='UTF-8')
handheight <- read.table("./Data/handheight.txt", header=T, encoding='UTF-8')
heightfoot <- read.table("./Data/height_foot.txt", header=T, encoding='UTF-8')
heightgpa <- read.table("./Data/heightgpa.txt", header=T, encoding='UTF-8')
heightweight <- read.table("./Data/student_height_weight.txt", header=T, encoding='UTF-8')
infectionrisk <- read.table("./Data/infectionrisk.txt", header=T, encoding='UTF-8')
influence1 <- read.table("./Data/influence1.txt", header=T, encoding='UTF-8')
influence2 <- read.table("./Data/influence2.txt", header=T, encoding='UTF-8')
influence3 <- read.table("./Data/influence3.txt", header=T, encoding='UTF-8')
influence4 <- read.table("./Data/influence4.txt", header=T, encoding='UTF-8')
iqsize <- read.table("./Data/iqsize.txt", header=T, encoding='UTF-8')
leukemia <- read.table("./Data/leukemia_remission.txt", header=T, encoding='UTF-8')
lungfunction <- read.table("./Data/fev_dat.txt", header=T, encoding='UTF-8')
mammgest <- read.table("./Data/mammgest.txt", header=T, encoding='UTF-8')
marketshare <- read.table("./Data/market_share.txt", header=T, encoding='UTF-8')
martian <- read.table("./Data/martian.txt", header=T, encoding='UTF-8')
newaccounts <- read.table("./Data/newaccounts.txt", header=T, encoding='UTF-8')
odor <- read.table("./Data/odor.txt", header=T, encoding='UTF-8')
oldfaithful <- read.table("./Data/oldfaithful.txt", header=T, encoding='UTF-8')
pastry <- read.table("./Data/pastry.txt", header=T, encoding='UTF-8')
peru <- read.table("./Data/peru.txt", header=T, encoding='UTF-8')
physical <- read.table("./Data/Physical.txt", header=T, encoding='UTF-8')
poisson <- read.table("./Data/poisson_simulated.txt", header=T, encoding='UTF-8')
poverty <- read.table("./Data/poverty.txt", header=T, encoding='UTF-8')
realestate_sales <- read.table("./Data/realestate_sales.txt", header=T, encoding='UTF-8')
realestate <- read.table("./Data/realestate.txt", header=T, encoding='UTF-8')
recovery <- read.table("./Data/recovery.txt", header=T, encoding='UTF-8')
shortleaf <- read.table("./Data/shortleaf.txt", header=T, encoding='UTF-8')
signdist <- read.table("./Data/signdist.txt", header=T, encoding='UTF-8')
skincancer <- read.table("./Data/skincancer.txt", header=T, encoding='UTF-8')
soapsuds <- read.table("./Data/soapsuds.txt", header=T, encoding='UTF-8')
solconc <- read.table("./Data/solutions_conc.txt", header=T, encoding='UTF-8')
sprinters <- read.table("./Data/mens200m.txt", header=T, encoding='UTF-8')
statfemales <- read.table("./Data/stat_females.txt", header=T, encoding='UTF-8')
swallows <- read.table("./Data/allswallows.txt", header=T, encoding='UTF-8')
toluca <- read.table("./Data/toluca.txt", header=T, encoding='UTF-8')
toxicity <- read.table("./Data/toxicity.txt", header=T, encoding='UTF-8')
treadwear <- read.table("./Data/treadwear.txt", header=T, encoding='UTF-8')
uncorrpreds <- read.table("./Data/uncorrpreds.txt", header=T, encoding='UTF-8')
wordrecall <- read.table("./Data/wordrecall.txt", header=T, encoding='UTF-8')
yield <- read.table("./Data/yield.txt", header=T, encoding='UTF-8')

colnames(alcoholarm)
colnames(alcoholtobacco)
colnames(allentest)
colnames(allentestn23)
colnames(alligator)
colnames(alphapluto)
colnames(anscombe)
colnames(babybirds)
colnames(birthsmokers)
colnames(blaisdell)
colnames(bldgstories)
colnames(bloodpress)
colnames(bluegills)
colnames(bodyfat)
colnames(ca_learning)
colnames(carstopping)
colnames(cement)
colnames(census)
colnames(coolhearts)
colnames(cordblood)
colnames(corrosion)
colnames(depression)
colnames(disease)
colnames(earthquakes)
colnames(employee)
colnames(exerimmun)
colnames(galton)
colnames(google)
colnames(handheight)
colnames(heightfoot)
colnames(heightgpa)
colnames(heightweight)
colnames(infectionrisk)
colnames(influence1)
colnames(influence2)
colnames(influence3)
colnames(influence4)
colnames(iqsize)
colnames(leukemia)
colnames(lungfunction)
colnames(mammgest)
colnames(marketshare)
colnames(martian)
colnames(newaccounts)
colnames(odor)
colnames(oldfaithful)
colnames(pastry)
colnames(peru)
colnames(physical)
colnames(poisson)
colnames(poverty)
colnames(realestate_sales)
colnames(realestate)
colnames(recovery)
colnames(shortleaf)
colnames(signdist)
colnames(skincancer)
colnames(soapsuds)
colnames(solconc)
colnames(sprinters)
colnames(statfemales)
colnames(swallows)
colnames(toluca)
colnames(toxicity)
colnames(treadwear)
colnames(uncorrpreds)
colnames(wordrecall)
colnames(yield)

View(alcoholarm)
View(alcoholtobacco)
View(allentest)
View(allentestn23)
View(alligator)
View(alphapluto)
View(anscombe)
View(babybirds)
View(birthsmokers)
View(blaisdell)
View(bldgstories)
View(bloodpress)
View(bluegills)
View(bodyfat)
View(ca_learning)
View(carstopping)
View(cement)
View(census)
View(coolhearts)
View(cordblood)
View(corrosion)
View(depression)
View(disease)
View(earthquakes)
View(employee)
View(exerimmun)
View(galton)
View(google)
View(handheight)
View(heightfoot)
View(heightgpa)
View(heightweight)
View(infectionrisk)
View(influence1)
View(influence2)
View(influence3)
View(influence4)
View(iqsize)
View(leukemia)
View(lungfunction)
View(mammgest)
View(marketshare)
View(martian)
View(newaccounts)
View(odor)
View(oldfaithful)
View(pastry)
View(peru)
View(physical)
View(poisson)
View(poverty)
View(realestate_sales)
View(realestate)
View(recovery)
View(shortleaf)
View(signdist)
View(skincancer)
View(soapsuds)
View(solconc)
View(sprinters)
View(statfemales)
View(swallows)
View(toluca)
View(toxicity)
View(treadwear)
View(uncorrpreds)
View(wordrecall)
View(yield)
